/* The map. In the real app this is hand-drawn SVG from a Survey-of-India
   district file via src/lib/projection.ts — 36 states, 760 districts, 454 rail
   lines, 8,696 station dots — generated by npm run assets and gitignored, so
   none of it is in the repository. This recreation draws the same three layers
   from public-domain Natural Earth geometry instead: sea, land, routes over a
   station field. No map library, per the project's hardest rule. */

function IndiaMap({ journeys, stations, onPickStation, seaPaused }) {
  const ref = React.useRef(null);
  const [box, setBox] = React.useState({ w: 900, h: 700 });

  React.useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const ro = new ResizeObserver(([e]) => {
      setBox({ w: e.contentRect.width, h: e.contentRect.height });
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const [land, setLand] = React.useState(null);
  React.useEffect(() => {
    d3.json('https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json').then((topo) => {
      const all = topojson.feature(topo, topo.objects.countries);
      setLand({
        india: all.features.find((c) => c.properties.name === 'India'),
        neighbours: all.features.filter((c) => ['Pakistan','Nepal','Bangladesh','Bhutan','Myanmar','Sri Lanka','China','Afghanistan'].includes(c.properties.name)),
      });
    });
  }, []);

  const byCode = React.useMemo(() => Object.fromEntries(stations.map((s) => [s.code, s])), [stations]);

  if (!land || box.w < 10) return <div ref={ref} style={{ position:'absolute', inset:0 }} />;

  const projection = d3.geoMercator().fitExtent([[24, 24], [box.w - 24, box.h - 24]], land.india);
  const path = d3.geoPath(projection);
  const at = (code) => { const s = byCode[code]; return s ? projection(s.lonlat) : null; };

  const legs = journeys.map((j) => ({ id: j.id, a: at(j.fromCode), b: at(j.toCode) })).filter((l) => l.a && l.b);
  const visited = new Set(journeys.flatMap((j) => [j.fromCode, j.toCode]));

  return (
    <div ref={ref} style={{ position:'absolute', inset:0, background:'var(--sea)' }}>
      <svg width={box.w} height={box.h} style={{ display:'block' }}>
        {/* graticule and neighbours are drawn ON the water in --sea-ink; decorative */}
        <g stroke="var(--sea-ink)" strokeWidth="0.5" opacity="0.28" fill="none">
          <path d={path(d3.geoGraticule().step([5,5])())} />
        </g>
        <g fill="var(--sea-ink)" opacity="0.13">
          {land.neighbours.map((c,i) => <path key={i} d={path(c)} />)}
        </g>

        {/* the country */}
        <path d={path(land.india)} fill="var(--land)" stroke="var(--line-strong)" strokeWidth="0.8" />

        {/* the station field — texture, not subject */}
        <g>
          {stations.map((s) => {
            const p = projection(s.lonlat);
            const seen = visited.has(s.code);
            return (
              <circle key={s.code} cx={p[0]} cy={p[1]} r={seen ? 3.5 : 2.2}
                fill={seen ? 'var(--station-seen)' : 'var(--dot)'} opacity={seen ? 1 : 0.6}
                style={{ cursor:'pointer' }}
                onClick={() => onPickStation && onPickStation(s)}>
                <title>{s.code} · {s.name}</title>
              </circle>
            );
          })}
        </g>

        {/* the route: a black line read through an --ink halo, the way a wet
            rail looks at night. Halo first, line on top. */}
        <g fill="none" strokeLinecap="round" strokeLinejoin="round">
          {legs.map((l) => (
            <path key={'h'+l.id} d={`M${l.a[0]} ${l.a[1]} L${l.b[0]} ${l.b[1]}`}
              stroke="var(--route-halo)" strokeWidth="7" opacity="0.3" />
          ))}
          {legs.map((l) => (
            <path key={l.id} d={`M${l.a[0]} ${l.a[1]} L${l.b[0]} ${l.b[1]}`}
              stroke="var(--route-taken)" strokeWidth="2.4" />
          ))}
        </g>

        {/* exactly one "you are here" */}
        {legs.length > 0 && (
          <g>
            <circle cx={legs[legs.length-1].b[0]} cy={legs[legs.length-1].b[1]} r="9"
              fill="var(--you-are-here)" opacity="0.2">
              {!seaPaused && <animate attributeName="r" values="7;13;7" dur="2.6s" repeatCount="indefinite" />}
            </circle>
            <circle cx={legs[legs.length-1].b[0]} cy={legs[legs.length-1].b[1]} r="4" fill="var(--you-are-here)" />
          </g>
        )}
      </svg>
      <p style={{
        position:'absolute', right:10, bottom:6, margin:0, fontSize:'var(--text-label)',
        letterSpacing:'var(--tracking-label)', textTransform:'uppercase', color:'var(--sea-ink)',
      }}>Natural Earth outline · recreation</p>
    </div>
  );
}

Object.assign(window, { IndiaMap });
